# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_name', models.CharField(max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latin_name', models.CharField(max_length=200)),
                ('height_m', models.IntegerField()),
                ('crown_m', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='TreeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=200)),
                ('picture', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='photos/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreeTrunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trunk_cm', models.IntegerField()),
                ('meas_height_cm', models.IntegerField(default='130')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Tree')),
            ],
        ),
    ]
