# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170807_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeimage',
            name='description',
        ),
    ]
