# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_treeimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='tree_number',
            field=models.IntegerField(default=0),
        ),
    ]
