# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 02:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import inventory.validators
import re


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_tree_tree_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='code',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z', 32), code='invalid', message='Numeric characters separated by - allowed.')]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tree',
            name='crown_m',
            field=models.IntegerField(blank=True, validators=[inventory.validators.validate_postive_int]),
        ),
        migrations.AlterField(
            model_name='tree',
            name='height_m',
            field=models.IntegerField(blank=True, validators=[inventory.validators.validate_postive_int]),
        ),
        migrations.AlterField(
            model_name='tree',
            name='latin_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tree',
            name='tree_number',
            field=models.IntegerField(default=0, validators=[inventory.validators.validate_tree_number]),
        ),
        migrations.AlterField(
            model_name='treetrunk',
            name='meas_height_cm',
            field=models.IntegerField(default='130', validators=[inventory.validators.validate_postive_int]),
        ),
        migrations.AlterField(
            model_name='treetrunk',
            name='trunk_cm',
            field=models.IntegerField(validators=[inventory.validators.validate_trunk]),
        ),
    ]
