# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20170810_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='crown_m',
            field=models.IntegerField(null=True, validators=[inventory.validators.validate_postive_int]),
        ),
        migrations.AlterField(
            model_name='tree',
            name='height_m',
            field=models.IntegerField(null=True, validators=[inventory.validators.validate_postive_int]),
        ),
    ]
