# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20170810_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='crown_m',
            new_name='crown_area',
        ),
        migrations.AddField(
            model_name='tree',
            name='crown_area_unit',
            field=models.TextField(blank=True),
        ),
    ]
