# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_tree_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=200)),
                ('picture', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='photos/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Tree')),
            ],
        ),
    ]
