# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20170812_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='crown_area_unit',
            field=models.CharField(choices=[('m', 'm'), ('m2', 'm2')], default='1', max_length=2),
        ),
    ]
