# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_treeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='inventory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tree',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
