# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20170430_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='crown_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tree',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
