# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20170501_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='circuit_cm',
        ),
    ]
