# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20170812_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymap',
            old_name='author',
            new_name='inventory',
        ),
    ]
