# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20170812_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeimage',
            name='picture',
            field=models.ImageField(default='no-img.jpg', upload_to='photos/'),
        ),
    ]
