# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20170812_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventorymap',
            name='picture',
            field=models.ImageField(default='no-map.jpg', upload_to='photos/maps/'),
        ),
    ]
