# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20170812_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeOnMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField(blank=True, null=True, validators=[inventory.validators.validate_postive_int])),
                ('y_pos', models.IntegerField(blank=True, null=True, validators=[inventory.validators.validate_postive_int])),
                ('radius', models.IntegerField(blank=True, null=True, validators=[inventory.validators.validate_postive_int])),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tree',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='treeonmap',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Tree'),
        ),
    ]
