# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20170813_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeonmap',
            name='map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.InventoryMap'),
            preserve_default=False,
        ),
    ]
