# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_treeonmap_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treeonmap',
            old_name='map',
            new_name='inventorymap',
        ),
    ]
