# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20170813_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeonmap',
            name='inventorymap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treesonmap', to='inventory.InventoryMap'),
        ),
    ]
