# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20170813_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeonmap',
            name='tree_number',
            field=models.IntegerField(default=0, validators=[inventory.validators.validate_postive_int]),
        ),
        migrations.AlterField(
            model_name='treeonmap',
            name='radius',
            field=models.IntegerField(default=10, validators=[inventory.validators.validate_postive_int]),
        ),
        migrations.AlterField(
            model_name='treeonmap',
            name='x_pos',
            field=models.IntegerField(default=0, validators=[inventory.validators.validate_postive_int]),
        ),
        migrations.AlterField(
            model_name='treeonmap',
            name='y_pos',
            field=models.IntegerField(default=0, validators=[inventory.validators.validate_postive_int]),
        ),
    ]
